### ISSUE TITLE
As of Jul 2023: Problems Installing Lpy binaries using Conda

### ISSUE THREAD

**Issue by deltayoung** [openalea/lpy#39]
I'm trying to install lpy using conda on one existing environment 
    conda install openalea.lpy -c fredboudon -c conda-forge
and one new environment:
    conda create -n lpy openalea.lpy -c fredboudon -c conda-forge

For the existing environment, strangely after installation and calling "lpy", there is nothing happening. However, for the new environment, "lpy" works and the visual lpy editor appear.
What did I do wrong for the existing environment?

**Comment by deltayoung** [comment]
i didn't manage to troubleshoot the existing environment, but moved on with the new environment that works just fine.

**Comment by wanghanruibaba** [comment]
lpy在cmd里面调用吗？我安装installration里面的提示，但是在调用lpy没有反应

**Comment by pradal** [comment]
Translation : Is lpy called inside cmd? I installed the prompts inside installration, but there is no response in calling lpy!

**Comment by blacall** [comment]
Bumping this issue.

Calling `lpy` does nothing.

Using Anaconda Prompt (Windows x64), my installation process was:

`git clone https://github.com/openalea/lpy.git`
`conda create -n lpy openalea.lpy -c fredboudon -c conda-forge`
`conda activate lpy`

Typing `lpy` into the terminal does nothing.
 Any tips?

**Comment by pradal** [comment]
Thanks for testing it.
Could you try to get LPy from the openalea repository?

```bash
conda create -n testlpy -c openalea3 -c conda-forge openalea.lpy
```

Then, type in the Anaconda prompt
```bash 
conda activate testlpy
lpy
```

**Comment by blacall** [comment]
@pradal Thank you for the quick response!

I've tried what you mentioned and calling `lpy` still does not open any GUI in the `testlpy` conda environment.

Not sure if this is helpful, but I have also tried creating the `cauliflower` conda environment (from [this](https://gitlab.inria.fr/mosaic/publications/cauliflower) repository) and calling `lpy` also does not work in there.

Here is the output from my `conda info`:
```active environment : testlpy
active env location : C:\Users\Kevin\miniconda3\envs\testlpy
shell level : 2
user config file : C:\Users\Kevin\.condarc
populated config files : C:\Users\Kevin\miniconda3\.condarc
conda version : 25.3.1
conda-build version : not installed
solver : libmamba (default)
virtual packages : __archspec=1=skylake
                          __conda=25.3.1=0
                          __cuda=12.8=0
                          __win=10.0.26100=0
base environment : C:\Users\Kevin\miniconda3  (writable)
conda av data dir : C:\Users\Kevin\miniconda3\etc\conda
conda av metadata url : None
channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
package cache : C:\Users\Kevin\miniconda3\pkgs
                          C:\Users\Kevin\.conda\pkgs
                          C:\Users\Kevin\AppData\Local\conda\conda\pkgs
envs directories : C:\Users\Kevin\miniconda3\envs
                          C:\Users\Kevin\.conda\envs
                          C:\Users\Kevin\AppData\Local\conda\conda\envs
platform : win-64
user-agent : conda/25.3.1 requests/2.32.3 CPython/3.13.2 Windows/11 Windows/10.0.26100 solver/libmamba conda-libmamba-solver/25.4.0 libmambapy/2.0.5 aau/0.7.0 c/. s/. e/.
administrator : True
netrc file : None
offline mode : False

**Comment by pradal** [comment]
Could you run in your just created environment

```bash
python -c 'from openalea.lpy.gui.lpystudio import main; main()'
```
And see if there is an error?

**Comment by blacall** [comment]
Here is the error it encountered:
```(testlpy) C:\Users\Kevin\git-downloads\lpy>python -c "from openalea.lpy.gui.lpystudio import main; main()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Kevin\miniconda3\envs\testlpy\Lib\site-packages\OpenAlea.Lpy-3.14.1-py3.12.egg\openalea\lpy\__init__.py", line 2, in <module>
    from .__lpy_kernel__ import *
ImportError: DLL load failed while importing __lpy_kernel__: The specified module could not be found.

**Comment by pradal** [comment]
Great. We are currently planning a release. When we will release LPy, we will ask you to test it again.
